[package]
name = "lazy-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.12.3"
tar = "0.4.38"
walkdir = "2.3.3"